<?php
/*
$title = 'News Categories';
$this->headTitle($title);
?>
<table class="table">
foreach ($rows as $row) : 
<tr>
	<td><?php echo $this->escapeHtml($row["id"]);?></td>
    <td><?php echo $this->escapeHtml($row["name"]);?></td>
    <td><?php echo $this->escapeHtml($row["alias"]);?></td>
    <td><?php echo $this->escapeHtml($row["description"]);?></td>
    <td><?php echo $this->escapeHtml($row["published"]);?></td>
    <td><?php echo $this->escapeHtml($row["access"]);?></td>
    <td><?php echo $this->escapeHtml($row["ordering"]);?></td>
</tr>
endforeach; 
</table>
**/
?>
